
📊 metrics embed:
  - changed-files:
    - any-glob-to-any-file:
      - source/app/action/**
      - source/app/web/**

✨ metrics insights:
  - changed-files:
    - any-glob-to-any-file:
      - source/app/web/statics/insights/**

🧩 plugins:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/**

🖼️ templates:
  - changed-files:
    - any-glob-to-any-file:
      - source/templates/**

🗃️ base:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/base/**

🧱 core:
  - changed-files:
    - any-glob-to-any-file:
      - source/app/metrics/**
      - source/plugins/core/**

🚀 ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

⚙️ ci config:
  - changed-files:
    - any-glob-to-any-file:
      - .github/config/**
      - .github/ISSUE_TEMPLATE/**
      - .github/FUNDING.yml
      - .github/pull_request_template.md

🦾 ci actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/actions/**

🦿 ci scripts:
  - changed-files:
    - any-glob-to-any-file:
      - .github/scripts/**

🖨️ ci docs:
  - changed-files:
    - any-glob-to-any-file:
      - .github/readme/**
      - .github/**/examples.yml
      - .github/**/*.md
      - '!.github/pull_request_template.md'
      - .github/architecture.svg
      - .github/scripts/markdown_example.mjs
      - .github/scripts/presets_example.mjs

🎲 community plugins:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/community/**

🏆 plugin achievements:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/achievements/**
📰 plugin activity:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/activity/**

🌸 plugin anilist:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/anilist/**

📆 plugin calendar:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/calendar/**

♐ plugin code:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/code/**

🏅 plugin contributors:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/contributors/**

💬 plugin discussions:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/discussions/**

🎟️ plugin followup:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/followup/**

🎫 plugin gists:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/gists/**

💡 plugin habits:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/habits/**

🙋 plugin introduction:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/introduction/**

📅 plugin isocalendar:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/isocalendar/**

🈷️ plugin languages:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/languages/**

🗳️ plugin leetcode:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/leetcode/**

📜 plugin licenses:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/licenses/**

👨‍💻 plugin lines:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/lines/**

🎼 plugin music:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/music/**

🎩 plugin notable:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/notable/**

⏱️ plugin pagespeed:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/pagespeed/**

🧑‍🤝‍🧑 plugin people:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/people/**

✒️ plugin posts:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/posts/**

🗂️ plugin projects:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/projects/**

🎭 plugin reactions:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/reactions/**

📓 plugin repositories:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/repositories/**

🗼 plugin rss:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/rss/**

🌇 plugin skyline:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/skyline/**

💕 plugin sponsors:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/sponsors/**

🗨️ plugin stackoverflow:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/stackoverflow/**

✨ plugin stargazers:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/stargazers/**

💫 plugin starlists:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/starlists/**

🌟 plugin stars:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/stars/**

💭 plugin support:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/support/**

📌 plugin topics:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/topics/**

🧮 plugin traffic:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/traffic/**

🐤 plugin tweets:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/tweets/**

⏰ plugin wakatime:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/wakatime/**

