name: Continuous integration

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build-test-analyze:
    name: Build, test and analyze
    if: "!contains(github.event.head_commit.message, '[skip test]')"
    uses: siosios/metrics/.github/workflows/test.yml@master

  format:
    name: Format code
    runs-on: self-hosted
    needs: build-test-analyze
    if: always() && (needs.build-test-analyze.result == 'success' || needs.build-test-analyze.result == 'skipped')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Format code
        run: |
          npm install -g dprint
          mkdir -v -p /home/runner/.cache/dprint/cache
          npx dprint fmt --config .github/config/dprint.json
      - name: Publish formatted code
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "chore: code formatting" || echo "No changes to commit"
          git push origin ${GITHUB_REF##*/}

  update-indexes:
    name: Publish rebuilt metrics indexes
    runs-on: self-hosted
    needs: format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup metrics
        run: npm install
      - name: Publish rebuild metrics indexes
        run: npm run build -- publish

  docker-master:
    name: Publish master to GitHub registry
    runs-on: self-hosted
    needs: update-indexes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub registry
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and publish docker image
        run: |
          docker build -t ghcr.io/siosios/metrics:master .
          docker push ghcr.io/siosios/metrics:master
      - name: Tag and publish beta and main images
        run: |
          METRICS_VERSION=$(cat package.json | grep -Po '(?<="version": ")\d+[.]\d+(?=[.]0-beta")')
          METRICS_VERSION_BETA="$METRICS_VERSION-beta"
          if [[ ! -z "$METRICS_VERSION" ]]; then
            docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:$METRICS_VERSION_BETA
            docker push ghcr.io/siosios/metrics:$METRICS_VERSION_BETA
          fi
          docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:main
          docker push ghcr.io/siosios/metrics:main

  deploy-master:
    name: Deploy siosios/metrics@master
    runs-on: self-hosted
    needs: docker-master
    steps:
      - name: Deploy web instance
        run: "curl -X POST -H 'Authorization: ${{ secrets.WEB_DEPLOY_BETA_TOKEN }}' https://beta-metrics.lecoq.io/.control/stop"
      - name: Wait for redeploy
        run: sleep 120
      - name: Check deployment status
        run: "curl --retry 15 --retry-delay 60 https://beta-metrics.lecoq.io/.version"

  action-master-test:
    name: Test siosios/metrics@master
    runs-on: self-hosted
    needs: docker-master
    steps:
      - name: Run tests
        uses: mikey-/metrics@main
        with:
          token: MOCKED_TOKEN
          plugins_errors_fatal: yes
          dryrun: yes
          use_mocked_data: yes
          verify: yes

  publish-examples:
    name: Publish examples
    needs: action-master-test
    uses: siosios/metrics/.github/workflows/examples.yml@master
    secrets:
      METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
      METRICS_TOKEN_WITH_SCOPES: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
      METRICS_TOKEN_PERSONAL: ${{ secrets.METRICS_TOKEN_PERSONAL }}
      CHESS_TOKEN: ${{ secrets.CHESS_TOKEN }}
      PAGESPEED_TOKEN: ${{ secrets.PAGESPEED_TOKEN }}
      GOOGLE_MAP_TOKEN: ${{ secrets.GOOGLE_MAP_TOKEN }}
      SPLATOON_TOKEN: ${{ secrets.SPLATOON_TOKEN }}
      SPLATOON_STATINK_TOKEN: ${{ secrets.SPLATOON_STATINK_TOKEN }}
      SIXTEEN_PERSONALITIES_URL: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
      SPOTIFY_TOKENS: ${{ secrets.SPOTIFY_TOKENS }}
      STOCK_TOKEN: ${{ secrets.STOCK_TOKEN }}
      TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}

  publish-examples-presets:
    name: Publish examples (presets)
    needs: action-master-test
    uses: siosios/metrics/.github/workflows/examples.presets.yml@master

  docker-release:
    name: Publish release to GitHub registry
    runs-on: self-hosted
    needs: publish-examples
    if: contains(github.event.head_commit.message, '[release]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub registry
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull and tag docker image
        run: |
          docker pull ghcr.io/siosios/metrics:master
          GITHUB_COMMIT_MESSAGE=${{ github.event.head_commit.message }}
          docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:$(echo $GITHUB_COMMIT_MESSAGE | grep -Po 'v\d+[.]\d+')
          docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:latest
      - name: Publish release and latest to GitHub registry
        run: |
          GITHUB_COMMIT_MESSAGE=${{ github.event.head_commit.message }}
          docker push ghcr.io/siosios/metrics:$(echo $GITHUB_COMMIT_MESSAGE | grep -Po 'v\d+[.]\d+')
          docker push ghcr.io/siosios/metrics:latest

  update-latest:
    name: Rebase latest on master
    runs-on: self-hosted
    needs: docker-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Rebase latest on master
        run: |
          git checkout latest
          git merge master
          git push origin latest

  action-latest-test:
    name: Test siosios/metrics@latest
    runs-on: self-hosted
    needs: update-latest
    steps:
      - name: Run tests
        uses: mikey-/metrics@latest
        with:
          token: MOCKED_TOKEN
          plugins_errors_fatal: yes
          dryrun: yes
          use_mocked_data: yes
          verify: yes

  deploy-latest:
    name: Deploy siosios/metrics@latest
    runs-on: self-hosted
    needs:
      - docker-release
      - deploy-master
    steps:
      - name: Deploy web instance
        run: "curl -X POST -H 'Authorization: ${{ secrets.WEB_DEPLOY_TOKEN }}' https://metrics.lecoq.io/.control/stop"
      - name: Wait for redeploy
        run: sleep 120
      - name: Check deployment status
        run: "curl --retry 15 --retry-delay 60 https://metrics.lecoq.io/.version"

  publish-release:
    name: Publish release
    runs-on: self-hosted
    needs:
      - action-latest-test
      - deploy-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Publish release
        run: node .github/scripts/release.mjs
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

