name: Continuous integration
permissions: write-all
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
  
jobs:
  #Build, test and analyze
  build-test-analyze:
    name: Build, test and analyze
    if: "!contains(github.event.head_commit.message, '[skip test]')"
    uses: siosios/Metrics/.github/workflows/test.yml@master


  # Format code
  format:
    name: Format code
    runs-on: self-hosted
    needs: [ build-test-analyze ]
    if: always() && (needs.build-test-analyze.result == 'success' || needs.build-test-analyze.result == 'skipped')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout master
        run: git checkout master
      - name: Format code
        run: |
          npm install -g dprint
          mkdir -v -p /home/runner/.cache/dprint/cache
          npx dprint fmt --config .github/config/dprint.json
      - name: Publish formatted code
        run: |
          set +e
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "chore: code formatting"
          git push
          set -e

  # Update plugins and template indexes, along with README.md
  update-indexes:
    name: Publish rebuilt Metrics indexes
    runs-on: self-hosted
    needs: [ format ]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Pull changes
        run: |
          git checkout master
          git pull
      - name: Setup Metrics
        run: npm install
      - name: npm audit
        run: npm audit fix --force
      - name: Publish rebuild Metrics indexes
        run: npm run build --publish

  # Build docker image from master and publish it to GitHub registry
  docker-master:
    name: Publish master to GitHub registry
    runs-on: self-hosted
    needs: [ update-indexes ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub registry
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build docker image
        run: docker build -t ghcr.io/siosios/Metrics:master .
      - name: Publish to GitHub registry
        run: docker push ghcr.io/siosios/Metrics:master
      - name: Tag docker image (beta) and publish to GitHub registry
        run: |
          set +e
          Metrics_VERSION=$(cat package.json | grep -Po '(?<="version": ")\d+[.]\d+(?=[.]0-beta")')
          Metrics_VERSION_BETA="$Metrics_VERSION-beta"
          set -e
          if [[ ! -z "$Metrics_VERSION" ]]; then
            echo "Beta version: v$Metrics_VERSION_BETA"
            docker tag ghcr.io/siosios/Metrics:master ghcr.io/siosios/Metrics:$(echo "v$Metrics_VERSION_BETA")
            docker push ghcr.io/siosios/Metrics:$(echo "v$Metrics_VERSION_BETA")
          fi
      - name: Tag docker image (master) and publish to GitHub registry
        run: |
          docker tag ghcr.io/siosios/Metrics:master ghcr.io/siosios/Metrics:master
          docker push ghcr.io/siosios/Metrics:master

  # Deploy to beta-Metrics.lecoq.io
  #deploy-master:
  #  name: Deploy siosios/Metrics@master
  #  runs-on: ubuntu-latest
  #  needs: [ docker-master ]
  #  steps:
  #    - name: Deploy web instance
  #      run: "curl -X POST -H 'Authorization: ${{ secrets.WEB_DEPLOY_BETA_TOKEN }}' https://beta-Metrics.lecoq.io/.control/stop"
   #   - name: Wait for redeploy
   #     run: sleep 120
   #   - name: Check deployment status
   #     run: "curl --retry 15 --retry-delay 60 https://beta-Metrics.lecoq.io/.version"

  # Test siosios/Metrics@master
  action-master-test:
    name: Test master
    runs-on: self-hosted
    needs: [ docker-master ]
    steps:
      - name: Run tests
        uses: siosios/Metrics@master
        with:
          token: MOCKED_TOKEN
          plugins_errors_fatal: yes
          dryrun: yes
          use_mocked_data: yes
          verify: yes

  # Publish examples
  publish-examples:
    name: Publish examples
    needs: [ action-master-test ]
    uses: siosios/Metrics/.github/workflows/examples.yml@master
    secrets:
      Metrics_TOKEN: ${{ secrets.Metrics_TOKEN }}
      Metrics_TOKEN_WITH_SCOPES: ${{ secrets.Metrics_TOKEN_WITH_SCOPES }}
      Metrics_TOKEN_PERSONAL: ${{ secrets.Metrics_TOKEN_PERSONAL }}
      CHESS_TOKEN: ${{ secrets.CHESS_TOKEN }}
      PAGESPEED_TOKEN: ${{ secrets.PAGESPEED_TOKEN }}
      GOOGLE_MAP_TOKEN: ${{ secrets.GOOGLE_MAP_TOKEN }}
      SPLATOON_TOKEN: ${{ secrets.SPLATOON_TOKEN }}
      SPLATOON_STATINK_TOKEN: ${{ secrets.SPLATOON_STATINK_TOKEN }}
      SPOTIFY_TOKENS: ${{ secrets.SPOTIFY_TOKENS }}
      STOCK_TOKEN: ${{ secrets.STOCK_TOKEN }}
      TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}

  # Publish examples (presets)
  publish-examples-presets:
    name: Publish examples (presets)
    needs: [ action-master-test ]
    uses: siosios/Metrics/.github/workflows/examples.presets.yml@master

  # Build docker image from master and publish it to GitHub registry with release tag
  docker-release:
    name: Publish release to GitHub registry
    runs-on: self-hosted
    needs: [ publish-examples ]
    if: contains(github.event.head_commit.message, '[release]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub registry
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull docker image (master)
        run: docker pull ghcr.io/siosios/Metrics:master
      - name: Tag docker image (release)
        env:
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: docker tag ghcr.io/siosios/Metrics:master ghcr.io/siosios/Metrics:$(echo $GITHUB_COMMIT_MESSAGE | grep -Po 'v\d+[.]\d+')
      - name: Publish release to GitHub registry
        env:
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: docker push ghcr.io/siosios/Metrics:$(echo $GITHUB_COMMIT_MESSAGE | grep -Po 'v\d+[.]\d+')
      - name: Tag docker image (latest)
        run: docker tag ghcr.io/siosios/Metrics:master ghcr.io/siosios/Metrics:latest
      - name: Publish latest to GitHub registry
        run: docker push ghcr.io/siosios/Metrics:latest

  # Rebase latest branch on master
  update-latest:
    name: Rebase latest on master
    runs-on: self-hosted
    needs: [ docker-release ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Metrics
        run: npm install
      - name: Pull
        run: git pull
      - name: Checkout latest
        run: git checkout latest
      - name: Rebase latest on master
        run: git merge master
      - name: Push latest
        run: git push origin latest

  # Test siosios/Metrics@latest
  action-latest-test:
    name: Test siosios/Metrics@latest
    runs-on: self-hosted
    needs: [ update-latest ]
    steps:
      - name: Run tests
        uses: siosios/Metrics@latest
        with:
          token: MOCKED_TOKEN
          plugins_errors_fatal: yes
          dryrun: yes
          use_mocked_data: yes
          verify: yes

  # Deploy to Metrics.lecoq.io
 # deploy-latest:
  #  name: Deploy siosios/Metrics@latest
  #  runs-on: ubuntu-latest
 #   needs: [ docker-release, deploy-master ]
 #   steps:
 #     - name: Deploy web instance
 #       run: "curl -X POST -H 'Authorization: ${{ secrets.WEB_DEPLOY_TOKEN }}' https://Metrics.lecoq.io/.control/stop"
  #    - name: Wait for redeploy
 #       run: sleep 120
 #     - name: Check deployment status
 #       run: "curl --retry 15 --retry-delay 60 https://Metrics.lecoq.io/.version"

  # Publish GitHub release
  publish-release:
    name: Publish release
    runs-on: self-hosted
    needs: [ action-latest-test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Metrics
        run: npm install
      - name: Publish release
        run: node .github/scripts/release.mjs
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
