name: Continuous integration
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  #Build, test and analyze
  build-test-analyze:
    name: Build, test and analyze
    if: "!contains(github.event.head_commit.message, '[skip test]')"
    uses: siosios/metrics/.github/workflows/test.yml@master

  # Format code
  format:
    name: Format code
    runs-on: self-hosted
    needs: [ build-test-analyze ]
    if: always() && (needs.build-test-analyze.result == 'success' || needs.build-test-analyze.result == 'skipped')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout master
        run: git checkout master
      - name: Format code
        run: |
          npm install -g dprint
          mkdir -v -p /home/runner/.cache/dprint/cache
          npx dprint fmt --config .github/config/dprint.json
      - name: Publish formatted code
        run: |
          set +e
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "chore: code formatting"
          git push
          set -e

  # Update plugins and template indexes, along with README.md
  update-indexes:
    name: Publish rebuilt metrics indexes
    runs-on: self-hosted
    needs: [ format ]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Pull changes
        run: |
          git checkout master
          git pull
      - name: Setup metrics
        run: npm install
      - name: npm audit
        run: npm audit fix --force
      - name: Publish rebuild metrics indexes
        run: npm run build --publish

  # Build docker image from master and publish it to GitHub registry
  docker-master:
    name: Publish master to GitHub registry
    runs-on: self-hosted
    permissions:
      packages: write
    needs: [ update-indexes ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry to allow pushing Docker images
      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
       #  registry: ghcr.io
      #   username: ${{ github.actor }}
      - name: Login to GitHub registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build docker image
        run: docker build -t ghcr.io/siosios/metrics:master .
      - name: Publish to GitHub registry
        run: docker push ghcr.io/siosios/metrics:master
      - name: Tag docker image (beta) and publish to GitHub registry
        run: |
          set +e
          METRICS_VERSION=$(cat package.json | grep -Po '(?<="version": ")\d+[.]\d+(?=[.]0-beta")')
          METRICS_VERSION_BETA="$METRICS_VERSION-beta"
          set -e
          if [[ ! -z "$METRICS_VERSION" ]]; then
            echo "Beta version: v$METRICS_VERSION_BETA"
            docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:$(echo "v$METRICS_VERSION_BETA")
            docker push ghcr.io/siosios/metrics:$(echo "v$METRICS_VERSION_BETA")
          fi
      - name: Tag docker image (master) and publish to GitHub registry
        run: |
          docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:master
          docker push ghcr.io/siosios/metrics:master

  # Deploy to beta-metrics.lecoq.io
  #deploy-master:
  #  name: Deploy siosios/metrics@master
  #  runs-on: ubuntu-latest
  #  needs: [ docker-master ]
  #  steps:
  #    - name: Deploy web instance
  #      run: "curl -X POST -H 'Authorization: ${{ secrets.WEB_DEPLOY_BETA_TOKEN }}' https://beta-metrics.lecoq.io/.control/stop"
   #   - name: Wait for redeploy
   #     run: sleep 120
   #   - name: Check deployment status
   #     run: "curl --retry 15 --retry-delay 60 https://beta-metrics.lecoq.io/.version"

  # Test siosios/metrics@master
  action-master-test:
    name: Test siosios/metrics@master
    runs-on: self-hosted
    needs: [ docker-master ]
    steps:
      - name: Run tests
        uses: siosios/metrics@master
        with:
          token: MOCKED_TOKEN
          plugins_errors_fatal: yes
          dryrun: yes
          use_mocked_data: yes
          verify: yes


  # Publish examples
  publish-examples:
    name: Publish examples
    needs: [ action-master-test ]
    uses: siosios/metrics/.github/workflows/examples.yml@master
    secrets:
      METRICS_TOKEN: ${{ github.token }}

  # Publish examples (presets)
  publish-examples-presets:
    name: Publish examples (presets)
    needs: [ action-master-test ]
    uses: siosios/metrics/.github/workflows/examples.presets.yml@master

  # Build docker image from master and publish it to GitHub registry with release tag
  docker-release:
    name: Publish release to GitHub registry
    runs-on: self-hosted
    needs: [ publish-examples ]
    if: contains(github.event.head_commit.message, '[release]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub registry
        run: echo ${{ secrets.METRICS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull docker image (master)
        run: docker pull ghcr.io/siosios/metrics:master
      - name: Tag docker image (release)
        env:
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:$(echo $GITHUB_COMMIT_MESSAGE | grep -Po 'v\d+[.]\d+')
      - name: Publish release to GitHub registry
        env:
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: docker push ghcr.io/siosios/metrics:$(echo $GITHUB_COMMIT_MESSAGE | grep -Po 'v\d+[.]\d+')
      - name: Tag docker image (latest)
        run: docker tag ghcr.io/siosios/metrics:master ghcr.io/siosios/metrics:latest
      - name: Publish latest to GitHub registry
        run: docker push ghcr.io/siosios/metrics:latest

  # Rebase latest branch on master
  update-latest:
    name: Rebase latest on master
    runs-on: self-hosted
    needs: [ docker-release ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup metrics
        run: npm install
      - name: Pull
        run: git pull
      - name: Checkout latest
        run: git checkout latest
      - name: Rebase latest on master
        run: git merge master
      - name: Push latest
        run: git push origin latest

  # Test siosios/metrics@master
  action-latest-test:
    name: Test siosios/metrics@master
    runs-on: self-hosted
    needs: [ update-latest ]
    steps:
      - name: Run tests
        uses: siosios/metrics@master
        with:
          token: MOCKED_TOKEN
          plugins_errors_fatal: yes
          dryrun: yes
          use_mocked_data: yes
          verify: yes

  # Deploy to metrics.lecoq.io
 # deploy-latest:
  #  name: Deploy siosios/metrics@master
  #  runs-on: ubuntu-latest
 #   needs: [ docker-release, deploy-master ]
 #   steps:
 #     - name: Deploy web instance
 #       run: "curl -X POST -H 'Authorization: ${{ secrets.WEB_DEPLOY_TOKEN }}' https://metrics.lecoq.io/.control/stop"
  #    - name: Wait for redeploy
 #       run: sleep 120
 #     - name: Check deployment status
 #       run: "curl --retry 15 --retry-delay 60 https://metrics.lecoq.io/.version"

  # Publish GitHub release
  publish-release:
    name: Publish release
    runs-on: self-hosted
    needs: [ action-latest-test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup metrics
        run: npm install
      - name: Publish release
        run: node .github/scripts/release.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
