name: Clean untagged docker images

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  clean:
    name: Clean untagged docker images
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Chmod script
        run: chmod +x .github/actions/ghcr-clean/delete_ghcr_dangling_images.sh
      - name: Run script
        run: ./delete_ghcr_dangling_images.sh siosios metrics
        working-directory: .github/actions/ghcr-clean
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
