name: Publish examples (presets)
on:
  schedule:
    - cron: "0 16 1/2 * *"
  workflow_dispatch:
  workflow_call:
jobs:
  examples:
    runs-on: self-josted
    if: "github.repository == 'siosios/metrics'"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup metrics
        run: npm install
      - name: Publish presets examples
        run: npm run presets -- publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

