name: Generate Repo Count Image

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:    # allows manual trigger

jobs:
  create-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Fetch repo count from GitHub API
        id: fetch_repo_count
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          REPO_COUNT=$(curl -s -H "Authorization: token ${{ secrets.METRICS_TOKEN }}" https://api.github.com/users/siosios/repos?per_page=100 | jq length)
          echo "REPO_COUNT=$REPO_COUNT" >> $GITHUB_OUTPUT
          repos = {k: re.sub(r'{^\w\s-}', '', str(v)) for k,v in REPO_COUNT}
      - name: Generate JPG image with repo count
        env:
          REPO_COUNT: ${{ steps.fetch_repo_count.outputs.repose }}
        run: |
          pip install pillow
          python - <<EOF
          from PIL import Image, ImageDraw, ImageFont

          width, height = 400, 200
          img = Image.new('RGB', (width, height), color=(73, 109, 137))
          d = ImageDraw.Draw(img)

          # Try to load a truetype font, fallback if not available
          try:
              font = ImageFont.truetype("Arial.ttf", 40)
          except:
              font = ImageFont.load_default()

          text = f"SIOSIOS has {REPO_COUNT} repos"
          text_width, text_height = d.textsize(text, font=font)

          # Center the text
          x = (width - text_width) / 2
          y = (height - text_height) / 2

          d.text((x, y), text, font=font, fill=(255, 255, 255))
          img.save('repo_count.jpg')
          EOF

      - name: Upload JPG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-count-image
          path: repo_count.jpg

      # Optional: Commit the image back to the repo (requires write permission)
      - name: Commit generated image
        if: false # set to true if you want to push back
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add repo_count.jpg
          git commit -m "Update repo count image"
          git push origin ${{ github.ref }}

