name: Repository Info Visualization
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight

jobs:
  visualize-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow pygithub pandas

      - name: Fetch and process repo data
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          python - <<EOF
          from github import Github
          from PIL import Image, ImageDraw, ImageFont
          import pandas as pd
          import re
          import io

          repos_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/siosios/repos?per_page=100&sort=updated")
          echo "repos_json=$repos_json" >> $GITHUB_OUTPUT

          # Regex to remove special chars and brackets [[]](https://stackoverflow.com/questions/63246546/remove-curly-brackets-at-the-end-of-values-in-column-of-dataframe)
          clean_data = {k: re.sub(r'{^\w\s-}', '', str(v)) for k,v in repos_json.items()}

          # Convert to DataFrame
          df = pd.DataFrame(list(clean_data.items()), columns=['Metric', 'Value'])

          # Create PNG image [[]](https://den.dev/blog/delete-all-github-workflow-runs-powershell/)
          img = Image.new('RGB', (800, 400), color=(240, 240, 240))
          d = ImageDraw.Draw(img)
          font = ImageFont.load_default(size=14)

          # Draw table
          x, y = 50, 50
          for index, row in df.iterrows():
              d.text((x, y), f"{row['Metric']}", font=font, fill='black')
              d.text((x+250, y), f"{row['Value']}", font=font, fill='black')
              y += 30

          # Add title
          d.text((50, 20), "$GITHUB_REPOSITORY Repository Information", font=font, fill='black')
          
          # Save image
          img.save('repo_info.png')
          EOF

      - name: Upload PNG artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-info
          path: repo_info.png
