name: Stale issues, pr and runs

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    name: Flag stale issues and pull requests
    runs-on: self-hosted
    steps:
      - uses: actions/stale@v6
        with:
          days-before-stale: -1
          stale-pr-message: This pull request seems to be inactive and will be automatically closed in a few days if it remains without any activity.
          days-before-pr-stale: 90
          days-before-pr-close: 7
          stale-pr-label: ⏹️ stale
          remove-stale-when-updated: yes
          exempt-issue-labels: 📦 dependencies
  lock:
    name: Lock inactive closed issues and pull requests
    needs:
      - stale
    runs-on: self-hosted
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 180
          issue-lock-reason: ""
          add-issue-labels: ☑️ archived
          pr-inactive-days: 180
          pr-lock-reason: ""
          add-pr-labels: ☑️ archived
  workflows:
    name: Remove expired workflow runs
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Chmod script
        run: chmod +x .github/actions/ghcr-clean/delete_workflows.sh
      - name: Run script
        run: ./delete_workflows.sh siosios/metrics
        working-directory: .github/actions/ghcr-clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
