name: Test (presets)

on:
  pull_request:
    branches: [ presets ]
  workflow_call:
    inputs:
      ref:
        type: string
      repo:
        type: string
jobs:

  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup metrics
        run: npm install
      - name: Run tests
        run: npm run test-presets
        env:
          HEAD_REF: ${{ inputs.ref }}
          REPO: ${{ inputs.repo }}
